### ISSUE TITLE
FactoryTestLauncher crashes with dual sim model

### ISSUE THREAD

**Issue by craftingmod** [wr3cckl3ss1/system3#2]
* Logcat
```
08-28 04:59:22.028 20183 20183 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method semGetSimState(I)I in class Landroid/telephony/TelephonyManager; or its super classes (declaration of 'android.telephony.TelephonyManager' appears in /system/framework/framework.jar!classes3.dex)
08-28 04:59:22.028 20183 20183 E AndroidRuntime:        at com.samsung.android.FactoryTestLauncher.modules.ModuleCommunication.getDSState(ModuleCommunication.java:202)
08-28 04:59:22.028 20183 20183 E AndroidRuntime:        at com.samsung.android.FactoryTestLauncher.ui.home.Home.refreshSimCard(Home.java:454)
08-28 04:59:22.028 20183 20183 E AndroidRuntime:        at com.samsung.android.FactoryTestLauncher.ui.home.Home.onResume(Home.java:70)
```

I'm sure someone will report this issue after October 31, 2023 so I'll write for now.

Reason: `semGetSimState` method doesn't exist in OneUI 5+. (framework.jar/classes3.dex)

If the guide would fix this issue when October, Please close this issue :)

**Comment by wr3cckl3ss1** [comment]
I assume you missed the part in the README about "YOU COULD". There are certain exceptions to this. You fall into this category. And there is nothing, you or I could do to change this unless you have root and can mount the system unfortunately. Good luck sir.

**Comment by craftingmod** [comment]
Thanks! :D
