### ISSUE TITLE
Unable to bypass the 3001 build type error. 

### ISSUE THREAD

**Issue by omaralwardian** [wr3cckl3ss1/system3#4]
![Screenshot_20230925_182948_Termux](https://github.com/wr3cckl3ss1/system3/assets/70217313/9ec0a204-4c40-4aba-8e5f-7294b60d13c0)

$ adb install -d -i prepackageinstaller /storage/emulated/0/
FTL-apk
Performing Streamed Install
adb: failed to install /storage/emulated/0/FTL.apk: Failure [-
3001: INSTALL_FAILED_REJECTED_BY_BUILDTYPE]
$

**Comment by wr3cckl3ss1** [comment]
I'll be nice here and assume you completely missed reading about how if something doesn't work....You need to TAKE IT UP WITH Samsung and not me. 

Secondly...your pic does nothing for me.
No device didnt info...no security patch info...

Lastly...it's PrePackageInstaller when you use it. NOT "prepackageinstaller"

**Comment by omaralwardian** [comment]
So you and I have already talked about this since when I first opened this ticket. Bye the disc in the readme where it says August and September I assumed it meant August and September are working. Either way, we have talked about this since then and it's all good I'll close this.

**Comment by RashadGasimly** [comment]
> So you and I have already talked about this since when I first opened this ticket. Bye the disc in the readme where it says August and September I assumed it meant August and September are working. Either way, we have talked about this since then and it's all good I'll close this.

yes, i agree. This method works on August patch but not September or newer patchs. Daddy Google is doing his job very well

**Comment by wr3cckl3ss1** [comment]
Daddy Google hasn't done a single thing here. Everything patched is solely because of Samsung. Now....I know everyone is dying for NEW...NEW...NEW. but in order for the NEW to happen. You have to go back. And if you're already screwed...then you're already screwed. I should just release everything now and end my headache that's been Non-Stop since this release and I think I will....
